// Compagno Federico 2101752

package com.compagnofederico.simon.components

import android.app.Application
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.viewModelScope
import com.compagnofederico.simon.database.Match
import com.compagnofederico.simon.database.MatchDatabase
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlin.collections.emptyList

/**
 * ViewModel class that manages the Simon game logic and state preservation.
 */
class GameViewModel(application: Application, private val savedStateHandle: SavedStateHandle): AndroidViewModel(application) {
    // List that stores the random color sequence generated by the computer
    private val computerSequence = mutableStateListOf<String>().apply {
        val savedSeq = savedStateHandle.get<ArrayList<String>>("saved_computer_seq")
        if (savedSeq != null) {
            addAll(savedSeq)
        }
    }
    // List that tracks the colors clicked by the user during their turn
    private val playerSequence = mutableStateListOf<String>()
    // Holds the identifier of the color button currently flashed
    var highlightedColor by mutableStateOf<String?>(null)
    // Available color initials used to build the Simon sequence
    private val simonColors = listOf("R", "G", "B", "M", "Y", "C")

    // Flag indicating if the computer is currently showing the sequence
    var isComputerPlaying by mutableStateOf(false)
    // State tracker checking if an active game match session is running
    var isGameStarted by mutableStateOf(savedStateHandle.get<Boolean>("saved_is_game_started") ?: false)
    // Pause state flag
    var isPaused by mutableStateOf(false)
    // Flag controlling whether the user is allowed to click the color buttons
    var isUserClickable by mutableStateOf(false)
    // Flag tracking if past match entries are loading from the database
    var isLoadingMatches by mutableStateOf(true)

    // Represents the currently selected match
    var selectedMatch by mutableStateOf<Match?>(null)
    // SoundHelper instance used to trigger gameplay sounds
    private val soundHelper: SoundHelper = SoundHelper(application)

    // Room database
    private val db = MatchDatabase.getDatabase(application)
    // DAO that handles the queries
    private val matchDao = db.matchDao()
    // Data holder containing the match history list
    val matchHistory = mutableStateOf<List<Match>>(emptyList())
    private var playJob: Job? = null

    init {
        // Resumes the sequence playback automatically if the app process was killed by the system (Case B)
        if (isGameStarted && computerSequence.isNotEmpty()) {
            playMatch()
        }
    }

    //Selects a specific match
    fun selectMatch(match: Match) {
        selectedMatch = match
    }

    // Toggles the pause state while the computer is demonstrating a color sequence
    fun togglePause(){
        if(isComputerPlaying){
            isPaused = !isPaused
        }
    }

    // Initializes a fresh game session
    fun startMatch(){
        isGameStarted = true
        savedStateHandle["saved_is_game_started"] = true
        computerSequence.clear()
        playerSequence.clear()
        computerSequence.add(simonColors.random())
        savedStateHandle["saved_computer_seq"] = ArrayList(computerSequence)
        playMatch()
    }

    // Extends the game sequence with a new color
    private fun addNewColor(){
        computerSequence.add(simonColors.random())
        playerSequence.clear()
        savedStateHandle["saved_computer_seq"] = ArrayList(computerSequence)
        playMatch()
    }

    // Asynchronous coroutine loop that handles the flashing of colors
    private fun playMatch(){
        playJob?.cancel()
        playJob = viewModelScope.launch{
            isUserClickable = false
            isComputerPlaying = true
            delay(1000)
            for(color in computerSequence){
                while(isPaused){
                    delay(1000)
                }
                if (!isActive) break
                highlightedColor = color
                soundHelper.playSound(color)
                delay(800)
                highlightedColor = null
                delay(200)
            }
            isComputerPlaying = false
            isUserClickable = true
        }
    }

    // Stops an active match session and saves results if the criteria are met
    fun onEndGame(){
        if(isGameStarted){
            if(computerSequence.size > 1){
                saveMatch(playerSequence.size)
            }
            gameEnded()
        }
    }

    // Clears the state when the game is finished
    private fun gameEnded(){
        playJob?.cancel()
        isGameStarted = false
        savedStateHandle["saved_is_game_started"] = false
        isPaused = false
        isComputerPlaying = false
        isUserClickable = false
        highlightedColor = null
        savedStateHandle.remove<ArrayList<String>>("saved_computer_seq")
    }

    // Validates the user input choices
    fun onUserClick(color: String){
        if(!isGameStarted || isComputerPlaying || !isUserClickable) return
        isUserClickable = false
        playJob?.cancel()
        playJob = viewModelScope.launch {
            playerSequence.add(color)
            highlightedColor = color
            soundHelper.playSound(color)
            delay(300)
            if (playerSequence[playerSequence.size - 1] == computerSequence[playerSequence.size - 1]) {
                highlightedColor = null
                if (playerSequence.size == computerSequence.size) {
                    delay(500)
                    if (isActive && isGameStarted) {
                        addNewColor()
                    }
                }else{
                    isUserClickable = true
                }
            } else {
                soundHelper.playSound("GAMEOVER")
                highlightedColor = null
                saveMatch(playerSequence.size - 1)
                isGameStarted = false
                savedStateHandle["saved_is_game_started"] = false
            }
        }
    }

    // Launches a IO coroutine thread to save game data records into the database
    fun saveMatch(errorIndex: Int){
        val score = computerSequence.size - 1
        val sequence = computerSequence.joinToString(", ")
        val errorIndex = if(errorIndex < 0) 0 else errorIndex
        viewModelScope.launch(Dispatchers.IO){
            val match = Match(score = score, sequence = sequence, errorPosition = errorIndex)
            matchDao.insertMatch(match)
        }
    }

    // Fetches the entire match collection from database and posts it to the Main thread UI
    fun loadMatches(){
        viewModelScope.launch(Dispatchers.IO){
            isLoadingMatches = true
            val matches = matchDao.getAllMatches()
            withContext(Dispatchers.Main){
                matchHistory.value = matches
                isLoadingMatches = false
            }
        }
    }
}